version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - set -e
      - echo "Packaging Lambda source"
      - rm -rf package lambda.zip
      - mkdir -p package
      - cp -r infra/dev/lambda_src/. package/
      - pushd package
      - zip -r ../lambda.zip .
      - popd
      - CURRENT_VERSION=$(aws lambda get-alias --function-name "$LAMBDA_FUNCTION_NAME" --name "$LAMBDA_ALIAS_NAME" --query 'FunctionVersion' --output text 2>/dev/null || echo "0")
      - echo "Current alias version: $CURRENT_VERSION"
      - aws lambda update-function-code --function-name "$LAMBDA_FUNCTION_NAME" --zip-file fileb://lambda.zip
      - TARGET_VERSION=$(aws lambda publish-version --function-name "$LAMBDA_FUNCTION_NAME" --query 'Version' --output text)
      - echo "Published version: $TARGET_VERSION"
      - >-
        printf 'version: 0.0\nResources:\n  - LambdaFunction:\n      Type: AWS::Lambda::Function\n      Properties:\n        Name: %s\n        Alias: %s\n        CurrentVersion: %s\n        TargetVersion: %s\n'
        "${LAMBDA_FUNCTION_NAME}"
        "${LAMBDA_ALIAS_NAME}"
        "${CURRENT_VERSION}"
        "${TARGET_VERSION}"
        > appspec.yml
      - cat appspec.yml
artifacts:
  files:
    - lambda.zip
    - appspec.yml
  discard-paths: yes
